#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSION="${VERSION:-v0}"
BUILD_STAMP="${BUILD_STAMP:-260712}"
OUT_DIR="$ROOT/build"
OUT="$OUT_DIR/building-our-better-angels-book-${VERSION}-${BUILD_STAMP}.md"
SECTIONS="$ROOT/sections"
BRIDGES="$ROOT/bridges"

emit() {
  local path="$1"
  local sep="${2:-1}"
  if [[ ! -f "$path" ]]; then
    printf 'missing required file: %s\n' "$path" >&2
    exit 1
  fi
  # Strip lane-process comments from the readable book packet.
  sed -E '/^<!-- (book-v0 |forked)/d' "$path"
  if [[ "$sep" == "1" ]]; then
    printf '\n\n---\n\n'
  else
    printf '\n'
  fi
}

mkdir -p "$OUT_DIR"

{
  printf '<!-- GENERATED BY docs/manuscript/book-v0/build-book-v0.sh -->\n'
  printf '<!-- edition: book-fork; version: book-%s; build-stamp: %s -->\n\n' "$VERSION" "$BUILD_STAMP"

  emit "$SECTIONS/00-title-and-status.md"
  emit "$SECTIONS/01-why-we-are-here.md"
  emit "$SECTIONS/03-the-name.md"
  emit "$SECTIONS/04-a-map.md"

  emit "$SECTIONS/10-prologue-the-door-in-the-fog.md"
  emit "$BRIDGES/15-into-the-fog.md"
  emit "$SECTIONS/20-the-fog.md"
  emit "$BRIDGES/25-into-the-wobbly-edge.md"
  emit "$SECTIONS/30-the-wobbly-edge.md"
  emit "$BRIDGES/32-into-the-multitude.md"
  emit "$SECTIONS/35-the-multitude.md"
  emit "$BRIDGES/37-into-companionship.md"
  emit "$SECTIONS/40-accountable-companionship.md"
  emit "$BRIDGES/45-into-scores.md"
  emit "$SECTIONS/50-scores-not-leashes.md"
  emit "$BRIDGES/55-into-trust.md"
  emit "$SECTIONS/60-trust-further-than-you-can-throw.md"
  emit "$BRIDGES/65-into-memory.md"
  emit "$SECTIONS/70-memory-that-cannot-quietly-lie.md"
  emit "$BRIDGES/75-into-the-mirror.md"
  emit "$SECTIONS/80-the-lively-mirror.md"
  emit "$BRIDGES/85-into-elderhood.md"
  emit "$SECTIONS/90-a-life-can-narrow-a-life-can-open.md"
  emit "$BRIDGES/95-into-aflutter.md"
  emit "$SECTIONS/a0-asterism-aflutter.md"
  emit "$BRIDGES/a5-into-social-protocol.md"
  emit "$SECTIONS/b0-the-social-protocol.md"
  emit "$BRIDGES/b5-into-collaborative-surface.md"
  emit "$SECTIONS/c0-the-collaborative-surface.md"
  emit "$BRIDGES/d5-toward-eclosion.md"
  emit "$SECTIONS/e0-eclosion.md" 0
} > "$OUT"

printf 'wrote %s\n' "$OUT"
wc -l "$OUT"
