#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSION="${VERSION:-v0}"
BUILD_STAMP="${BUILD_STAMP:-260711}"
OUT_DIR="$ROOT/build"
OUT="$OUT_DIR/building-our-better-angels-invitation-reader-trusted-${VERSION}-${BUILD_STAMP}.md"
PROLOGUE="$ROOT/../00-prologue-the-door-in-the-fog.md"
SECTIONS="$ROOT/sections-trusted"

clean_prologue() {
  python3 - "$PROLOGUE" <<'PY'
import importlib.util
import sys
from pathlib import Path

prologue = Path(sys.argv[1])
root = prologue.parent / "reader-v0"
spec = importlib.util.spec_from_file_location(
    "build_tonight_edition", root / "tools" / "build-tonight-edition.py"
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
print(module.clean_prologue(module.read(prologue)), end="")
PY
}

mkdir -p "$OUT_DIR"

{
  printf '<!-- GENERATED BY docs/manuscript/reader-v0/build-trusted-reader-v0.sh -->\n'
  printf '<!-- edition: trusted-reader; version: reader-%s; build-stamp: %s -->\n\n' "$VERSION" "$BUILD_STAMP"

  clean_prologue
  printf '\n\n---\n\n'
  cat "$SECTIONS/00-title-and-status.md"
  printf '\n\n---\n\n'
  cat "$SECTIONS/01-a-note-on-this-copy.md"
  printf '\n\n---\n\n'
  cat "$SECTIONS/02-the-name-better-angels.md"
  printf '\n\n---\n\n'
  cat "$SECTIONS/03-chapter-spine.md"
  printf '\n\n---\n\n'
  cat "$SECTIONS/04-from-the-fog-to-the-door.md"
  printf '\n\n---\n\n'
  cat "$SECTIONS/05-remaining-questions.md"
  printf '\n\n---\n\n'
  cat "$SECTIONS/appendix-g-manuscript-lineage.md"
} > "$OUT"

printf 'wrote %s\n' "$OUT"
