#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSION="${VERSION:-v0}"
BUILD_STAMP="${BUILD_STAMP:-260710}"
OUT_DIR="$ROOT/build"
OUT="$OUT_DIR/building-our-better-angels-invitation-reader-${VERSION}-${BUILD_STAMP}.md"
PROLOGUE="$ROOT/../00-prologue-the-door-in-the-fog.md"

mkdir -p "$OUT_DIR"

{
  printf '<!-- GENERATED BY docs/manuscript/reader-v0/build-reader-v0.sh -->\n'
  printf '<!-- version: reader-%s; build-stamp: %s -->\n\n' "$VERSION" "$BUILD_STAMP"

  cat "$ROOT/sections/00-title-and-status.md"
  printf '\n\n---\n\n'
  cat "$ROOT/sections/01-how-to-read.md"
  printf '\n\n---\n\n'
  cat "$PROLOGUE"
  printf '\n\n_Reader-v0 source note: prologue imported from docs/manuscript/00-prologue-the-door-in-the-fog.md._\n'
  printf '\n\n---\n\n'
  cat "$ROOT/sections/02-chapter-spine.md"
  printf '\n\n---\n\n'
  cat "$ROOT/sections/03-field-notes.md"
  printf '\n\n---\n\n'
  cat "$ROOT/sections/04-open-gates.md"
  printf '\n\n---\n\n'
  cat "$ROOT/sections/appendix-g-manuscript-lineage.md"
} > "$OUT"

printf 'wrote %s\n' "$OUT"

